### ISSUE TITLE
APR error 

### ISSUE THREAD

**Issue by rehan1988** [GilsonLabUCSD/APR#7]
am tring to follow this tutorial  http://ambermd.org/tutorials/advanced/tutorial29/APR_section1.html

I copied the directory apr.tar.gz
but python script failed with this error after running 

python2 apr.py eq -i apr.in -s continue

Setting up the APR framework ...
Continue mode enabled. Checking previous simulations ...
pmemd.cuda is on.
Translational and rotational restraints will be imposed.
No conformational restraints applied.
Hydrogen mass repartitioning (HMR) is on.

You can use Ctrl+C to quit the program.

Traceback (most recent call last):
  File "apr.py", line 1190, in <module>
    main()
  File "apr.py", line 1165, in main
    this.run_setup()
  File "apr.py", line 893, in run_setup
    tleap_in =  open('windows/a00/tleap.in','r')
IOError: [Errno 2] No such file or directory: 'windows/a00/tleap.in'

I have amber2020 installed on my cluster but I also checked it with amber12 same error comes.

One more question:
Please tell me can I use this sampling method to study the ligand dissociation. 

Thank you for your time in advance

Please guide me why the tleap script not copied in the windows files

Looking forward to hearing from you.

**Comment by slochower** [comment]
Hi @rehan1988. I'm not sure about the error that you encountered here. This code has largely been superseded by `paprika`. I see you have also posted an issue there and I think that is the best place to continue debugging. (If I had to guess, this error occurred because you asked the APR scripts to continue an existing run, so it looked for existing files.)
